In [100]:
from causalnex.structure.notears import from_pandas
from causalnex.network import BayesianNetwork 
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

In [101]:
#read data from file

data = pd.read_csv('FinalData.csv')
#data = data.drop(columns=drop_col)
data.head(5)

,DrugUse,MentalHealth,Age,EmploymentStatus,Sex,IncomeLevel,UrbanRural,EducationLevel
0,1,0,1,1,1,1,0,1
1,1,0,1,1,1,1,1,1
2,0,0,1,1,0,1,1,1
3,0,0,1,1,1,1,1,1
4,0,0,1,0,0,1,1,1

In [102]:
#preprocess data
struct_data = data.copy()
non_numeric_columns = list(struct_data.select_dtypes(exclude=[np.number]).columns)

le = LabelEncoder()

for col in non_numeric_columns:
    struct_data[col] = le.fit_transform(struct_data[col])

struct_data.head(5)

,DrugUse,MentalHealth,Age,EmploymentStatus,Sex,IncomeLevel,UrbanRural,EducationLevel
0,1,0,1,1,1,1,0,1
1,1,0,1,1,1,1,1,1
2,0,0,1,1,0,1,1,1
3,0,0,1,1,1,1,1,1
4,0,0,1,0,0,1,1,1

In [103]:
#learn causal model
import networkx as nx

tb_edges = [("IncomeLevel", "Age"), ("UrbanRural", "Age"), ("EmploymentStatus", "Age"), ("EducationLevel", "Age"), ("DrugUse", "Age"), ("Sex", "Age"), ("MentalHealth", "Age"),
            ("IncomeLevel", "Sex"), ("UrbanRural", "Sex"), ("EmploymentStatus", "Sex"), ("EducationLevel", "Sex"), ("DrugUse", "Sex"), ("Age", "Sex"), ("MentalHealth", "Sex"),
            ("Age", "UrbanRural"), ("Sex", "UrbanRural")]
sm = from_pandas(struct_data,tabu_edges=tb_edges, w_threshold=0.2)
print(sm)

nx.drawing.nx_pydot.write_dot(sm, 'noTears.dot')
print("Learned causal model")

StructureModel with 8 nodes and 9 edges
Learned causal model

In [105]:
#plot causal discovery graph
from IPython.display import Image
from causalnex.plots import plot_structure, NODE_STYLE, EDGE_STYLE
import pygraphviz

viz = plot_structure(
    sm,
    graph_attributes={"scale": "1.0"},
    all_node_attributes=NODE_STYLE.WEAK,
    all_edge_attributes=EDGE_STYLE.WEAK,
    prog='fdp',
)
filename = "./noTears02.png"
Image(viz.draw(filename))
print("Done")

Done